### ISSUE TITLE
This no longer works for me

### ISSUE THREAD

**Issue by buurro** [enriquegh/spotify-webplayer-token#1]
On the Spotify Web login page there's a reCAPTCHA button that I never noticed before, so that may be the reason.

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login
```

**Comment by rubenvde** [comment]
It looks like this is the same for me too

**Comment by Tsjippy** [comment]
I have the same issue:
`File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python2.7/site-packages/spotify_token.py", line 69, in start_session
    _login(session, cookies, username, password, token)
  File "/home/pi/.local/lib/python2.7/site-packages/spotify_token.py", line 31, in _login
    response.raise_for_status()
  File "/home/pi/.local/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login`

I have the same issue on Python3

**Comment by maschhoff** [comment]
Hi, will this be updated? 
It is although used in pychromecast and it would be bad if we can´t use it anymore
Heres  a solution maybe:
https://stackoverflow.com/questions/53771382/requests-exceptions-httperror-400-client-error-bad-request-for-url-https-ac

**Comment by kingosticks** [comment]
Works fine for me. And I don't get any reCAPTCHA either, I expect that might depend on your IP address.

**Comment by fabiopedrosa** [comment]
Could we get this fix integrated onto spotify_token? https://github.com/fondberg/spotcast/issues/34#issuecomment-537560108

**Comment by enriquegh** [comment]
@fabiopedrosa I'll try to get this in soon but PRs are welcome

**Comment by toabi** [comment]
Hm weird, I get the same error `requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login` with the latest version

**Comment by enriquegh** [comment]
@toabi worked for me using Python 3.7.4
Can you confirm you're using the latest version of the package?
You can do something like:

```bash
$ pip show spotify_token | grep Version
Version: 0.1.1
```
You should see 0.1.1

**Comment by toabi** [comment]
I just tried it again:

    ➜ pip show spotify_token | grep Version
    Version: 0.1.2

When running my script it produces the same traceback:

```
Traceback (most recent call last):
  File "spotify_example.py", line 84, in <module>
    data = st.start_session(args.user, args.password)
  File "X/venv/lib/python3.7/site-packages/spotify_token.py", line 75, in start_session
    _login(session, cookies, username, password, token)
  File "X/venv/lib/python3.7/site-packages/spotify_token.py", line 33, in _login
    response.raise_for_status()
  File "X/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login
```

**Comment by toabi** [comment]
OMG. I just found out it's just because my password was not correct. The error for wrong password is apparently also HTTP 400.

**Comment by enriquegh** [comment]
@toabi good to hear this worked now!
I agree, the 400 is a bit confusing.
I created #4 to bubble up the error response and make what's happening more obvious.
