### ISSUE TITLE
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested

### ISSUE THREAD

**Issue by barkinunal** [enriquegh/spotify-webplayer-token#5]
It gives this error in start_session

```
Traceback (most recent call last):
  File "bot.py", line 23, in <module>
    data = st.start_session(sys.argv[1], sys.argv[2])
  File "/Users/-/Documents/Side Projects/spotify-bot/lib/python3.7/site-packages/spotify_token.py", line 76, in start_session
    access_token, expiration_date = _get_access_token(session, cookies)
  File "/Users/-/Documents/Side Projects/spotify-bot/lib/python3.7/site-packages/spotify_token.py", line 45, in _get_access_token
    xml_tree = BeautifulSoup(data, 'lxml')
  File "/Users/-/Documents/Side Projects/spotify-bot/lib/python3.7/site-packages/bs4/__init__.py", line 228, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

```

**Comment by enriquegh** [comment]
@barkinunal 
What version of Python are you using?
Did you install spotify_token via pip? (i.e. `pip install spotify_token`)
Can you do a:
```
pip list
```
and post the output?

**Comment by enriquegh** [comment]
Closing issue. Please reopen if you still need help.

**Comment by barkinunal** [comment]
Sorry for the delay. I'm using Python 3.7.6
Yes, I installed it via pip. (pip3 install spotify_token)
This is my `pip3 list` output

Package            Version
------------------ ----------
astroid            2.2.5
blis               0.4.1
boto3              1.12.11
botocore           1.15.11
catalogue          1.0.0
certifi            2019.11.28
chardet            3.0.4
Click              7.0
cymem              2.0.3
docutils           0.15.2
en-core-web-sm     2.2.5
ffmpy              0.2.2
filelock           3.0.12
ftfy               4.4.3
html5lib           1.0.1
idna               2.8
importlib-metadata 1.5.0
isort              4.3.21
jmespath           0.9.5
joblib             0.14.1
lazy-object-proxy  1.4.2
mccabe             0.6.1
murmurhash         1.0.2
numpy              1.17.4
oauthlib           3.1.0
opencv-python      4.1.2.30
Pillow             7.0.0
pip                19.3.1
plac               1.1.3
preshed            3.0.2
pylint             2.3.1
PySocks            1.7.1
python-dateutil    2.8.1
regex              2020.2.20
requests           2.22.0
requests-oauthlib  1.3.0
s3transfer         0.3.3
sacremoses         0.0.38
sentencepiece      0.1.85
setuptools         42.0.2
six                1.12.0
spacy              2.2.3
spotipy            2.9.0
srsly              1.0.1
thinc              7.3.1
tokenizers         0.5.2
torch              1.4.0
torchvision        0.5.0
tqdm               4.43.0
transformers       2.5.1
tweepy             3.8.0
typed-ast          1.4.0
urllib3            1.25.7
wasabi             0.6.0
wcwidth            0.1.8
webencodings       0.5.1
wheel              0.33.6
wrapt              1.11.2
zipp               3.0.0

**Comment by enriquegh** [comment]
Thanks @barkinunal!
Some things that I see/don't see:

- I don't see spotify-token as a package that is installed.
- I don't beautifulsoup4 nor lxml which are what are the packages we need and are erring out

Could you try doing:
```
pip3 uninstall spotify_token
pip3 install spotify_token
```
and adding the result here in a gist.
I suspect that beautifulsoup is not being installed either because an old version of spotify_token is being installed or something else is happening.

**Comment by barkinunal** [comment]
I forgot I was using virtualenv, sorry about that. This is the list of my virtualenv : 

Package           Version
----------------- ----------
beautifulsoup4    4.8.2
bs4               0.0.1
certifi           2019.11.28
chardet           3.0.4
Click             7.0
Flask             1.1.1
Flask-OAuthlib    0.9.5
idna              2.9
itsdangerous      1.1.0
Jinja2            2.11.1
lxml              4.5.0
MarkupSafe        1.1.1
oauthlib          3.1.0
pip               20.0.2
PySocks           1.7.1
requests          2.23.0
requests-oauthlib 1.3.0
setuptools        41.2.0
six               1.14.0
soupsieve         2.0
spotify-token     0.1.2
spotipy           2.9.0
tweepy            3.8.0
urllib3           1.25.8
Werkzeug          1.0.0

**Comment by enriquegh** [comment]
@barkinunal my best guess is that whatever env you are using has an issue with lxml and how it was installed

Some things you could try:
- Completely nuke your virtualenv and start again.
Make sure that beautifulsoup4 and lxml are getting installed
You can try something like:
```bash
python3 -c "import lxml; print(lxml)"
```
- Add -v option to Python when running your script to get detailed data on what is happening when imports are happening.
This would look like:
```bash
python3 -v myscript.py
```

If you're still running into issues, you can send me the output as a gist and I can try and see if I can help more.
