### ISSUE TITLE
errorInvalidCredentials, but login&password are correct

### ISSUE THREAD

**Issue by De-Os** [enriquegh/spotify-webplayer-token#7]
After last update can't get token
![image](https://user-images.githubusercontent.com/37545373/82181509-54765880-98eb-11ea-85e4-d0657117c89b.png)
Login and password are 100% correct

**Comment by muhammedfurkan** [comment]
same issue

**Comment by enriquegh** [comment]
@De-Os @muhammedfurkan 
This is a known issue.
See #6 for more info.
