### ISSUE TITLE
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://open.spotify.com/get_access_token?reason=transport&productType=web_player

### ISSUE THREAD

**Issue by Esamanoaz** [enriquegh/spotify-webplayer-token#9]
This is a new error for me.
`requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://open.spotify.com/get_access_token?reason=transport&productType=web_player`

Full error logs in console: https://pastebin.com/SyhZ7Gyz

I don't know what else to say about this. Is this just Spotify's servers going down or is it something wrong that I am doing?

**Comment by Esamanoaz** [comment]
@enriquegh

**Comment by Esamanoaz** [comment]
Maybe I was doing too many requests? I accidentally put in a while loop to start_playback() for around 10 seconds until I realized and closed it. The program works fine now.

**Comment by enriquegh** [comment]
Sounds good! Does look like a rate limit of sorts from Spotify. 
Will close this.
